trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   cmake -S. -Bbuild 
   cmake --build build
  displayName: 'Command Line Script'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'